import {
  AgentDefinition,
  type CapabilityId,
  type McpToolName,
} from "@procurement/contracts";

const destructiveTools = [
  "documents.delete",
  "files.delete",
] as const satisfies readonly McpToolName[];

function definition(input: AgentDefinition): AgentDefinition {
  return AgentDefinition.parse(input);
}

export const capabilityRegistry: Readonly<Record<CapabilityId, AgentDefinition>> = {
  domain_search: definition({
    capability: "domain_search",
    role: "Domain Search Agent",
    responsibility: "Искать и первично классифицировать закупки по профилю направления.",
    allowedTools: [
      "procurement.search",
      "procurement.get",
      "procurement.get_lots",
      "procurement.get_status",
    ],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send"],
    contextRequirements: ["event", "intent", "domain_profile", "constraints"],
    minConfidence: 0.7,
    timeoutMs: 60_000,
    maxRetries: 2,
  }),
  document_ingest: definition({
    capability: "document_ingest",
    role: "Document Agent",
    responsibility: "Получать документы закупки и извлекать текст и таблицы.",
    allowedTools: [
      "procurement.get_documents",
      "documents.list",
      "documents.download",
      "documents.extract_text",
      "documents.extract_tables",
      "documents.ocr",
      "files.put",
      "files.get",
      "files.exists",
    ],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send"],
    contextRequirements: ["event", "intent", "domain_profile", "constraints", "procurement"],
    minConfidence: 0.75,
    timeoutMs: 180_000,
    maxRetries: 2,
  }),
  commercial_terms: definition({
    capability: "commercial_terms",
    role: "Commercial Terms Agent",
    responsibility: "Извлекать подтверждённые условия оплаты, поставки и обеспечения.",
    allowedTools: ["documents.search", "documents.get_page", "memory.get"],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send"],
    contextRequirements: [
      "event",
      "intent",
      "domain_profile",
      "constraints",
      "procurement",
      "documents",
    ],
    minConfidence: 0.8,
    timeoutMs: 120_000,
    maxRetries: 1,
  }),
  auction_analysis: definition({
    capability: "auction_analysis",
    role: "Auction Analysis Agent",
    responsibility: "Анализировать параметры и ход аукционной процедуры.",
    allowedTools: [
      "procurement.get",
      "procurement.get_status",
      "procurement.get_history",
      "procurement.get_documents",
      "documents.search",
      "documents.get_page",
    ],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send"],
    contextRequirements: ["event", "intent", "constraints", "procurement", "documents"],
    minConfidence: 0.75,
    timeoutMs: 120_000,
    maxRetries: 1,
  }),
  risk_analysis: definition({
    capability: "risk_analysis",
    role: "Risk Analysis Agent",
    responsibility: "Выявлять подтверждённые риски и противоречия без вычисления score.",
    allowedTools: [
      "documents.search",
      "documents.get_page",
      "memory.get",
      "knowledge.search",
    ],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send"],
    contextRequirements: [
      "event",
      "intent",
      "domain_profile",
      "constraints",
      "procurement",
      "documents",
      "company_knowledge",
    ],
    minConfidence: 0.8,
    timeoutMs: 120_000,
    maxRetries: 1,
  }),
  monitoring: definition({
    capability: "monitoring",
    role: "Monitoring Agent",
    responsibility: "Проверять изменения статуса, сроков и документов закупки.",
    allowedTools: [
      "procurement.get_status",
      "procurement.get_changes",
      "procurement.get_documents",
      "memory.get",
      "memory.put",
    ],
    forbiddenTools: [...destructiveTools, "telegram.send"],
    contextRequirements: [
      "event",
      "intent",
      "domain_profile",
      "constraints",
      "procurement",
      "relevant_history",
    ],
    minConfidence: 0.8,
    timeoutMs: 90_000,
    maxRetries: 2,
  }),
  notification: definition({
    capability: "notification",
    role: "Notification Agent",
    responsibility: "Подготавливать и отправлять разрешённые уведомления специалисту.",
    allowedTools: ["notification.send", "telegram.send"],
    forbiddenTools: [...destructiveTools, "memory.put"],
    contextRequirements: ["event", "intent", "procurement", "relevant_history"],
    minConfidence: 0.85,
    timeoutMs: 30_000,
    maxRetries: 1,
  }),
  report: definition({
    capability: "report",
    role: "Report Agent",
    responsibility: "Собирать проверенные результаты агентов в понятный отчёт.",
    allowedTools: [
      "documents.search",
      "documents.get_page",
      "memory.get",
      "knowledge.search",
    ],
    forbiddenTools: [...destructiveTools, "notification.send", "telegram.send", "memory.put"],
    contextRequirements: [
      "event",
      "intent",
      "domain_profile",
      "constraints",
      "procurement",
      "documents",
      "relevant_history",
      "company_knowledge",
    ],
    minConfidence: 0.85,
    timeoutMs: 120_000,
    maxRetries: 1,
  }),
};
