import { z } from "zod";
import { Confidence, IsoDateTime } from "./common.js";
import {
  DecisionId,
  FactId,
  ProcurementId,
  RiskId,
  ScoreSnapshotId,
  TaskId,
  UserId,
} from "./ids.js";
import { HumanDecisionKind } from "./task.js";

export const RiskSeverity = z.enum(["low", "medium", "high", "critical"]);
export type RiskSeverity = z.infer<typeof RiskSeverity>;

export const RiskType = z.enum([
  "short_deadline",
  "bad_payment_terms",
  "large_advance_required",
  "no_advance",
  "bid_security",
  "contract_security",
  "penalties",
  "experience_requirements",
  "complex_technical_requirements",
  "warranty_obligations",
  "non_standard_conditions",
  "legal",
  "commercial",
]);
export type RiskType = z.infer<typeof RiskType>;

export const Risk = z.object({
  id: RiskId,
  procurementId: ProcurementId,
  type: RiskType,
  severity: RiskSeverity,
  description: z.string().min(1),
  /** Risks inherit provenance from the facts that produced them. */
  factIds: z.array(FactId).min(1, "a risk must be grounded in at least one fact"),
  confidence: Confidence,
  detectedBy: z.string().min(1),
  detectedAt: IsoDateTime,
});
export type Risk = z.infer<typeof Risk>;

export const ScoreComponent = z.enum([
  "technical",
  "commercial",
  "deadline",
  "risk",
  "companyMatch",
]);
export type ScoreComponent = z.infer<typeof ScoreComponent>;

/** Normalised 0..1 component inputs, each computed from facts by pure code. */
export const ScoreComponents = z.object({
  technical: z.number().min(0).max(1),
  commercial: z.number().min(0).max(1),
  deadline: z.number().min(0).max(1),
  risk: z.number().min(0).max(1),
  companyMatch: z.number().min(0).max(1),
});
export type ScoreComponents = z.infer<typeof ScoreComponents>;

/**
 * Configurable and versioned. Changing weights produces a new snapshot rather
 * than mutating history, so past decisions stay explainable.
 */
export const ScoringFormula = z.object({
  id: z.string().min(1),
  version: z.number().int().positive(),
  weights: z.object({
    technical: z.number().min(0),
    commercial: z.number().min(0),
    deadline: z.number().min(0),
    risk: z.number().min(0),
    companyMatch: z.number().min(0),
  }),
  /** Points subtracted from the final score per risk of each severity. */
  riskPenalty: z.object({
    low: z.number().min(0),
    medium: z.number().min(0),
    high: z.number().min(0),
    critical: z.number().min(0),
  }),
  /** `accept` must not be below `review`; everything under `review` is rejected. */
  thresholds: z
    .object({
      review: z.number().min(0).max(100),
      accept: z.number().min(0).max(100),
    })
    .refine((t) => t.accept >= t.review, {
      message: "accept threshold must be greater than or equal to review threshold",
    }),
  /** Aggregate confidence below this escalates instead of deciding. */
  minConfidence: Confidence,
});
export type ScoringFormula = z.infer<typeof ScoringFormula>;

export const ScoreVerdict = z.enum(["accept", "review", "reject", "needs_human"]);
export type ScoreVerdict = z.infer<typeof ScoreVerdict>;

export const ScoreSnapshot = z.object({
  id: ScoreSnapshotId,
  procurementId: ProcurementId,
  formulaId: z.string().min(1),
  formulaVersion: z.number().int().positive(),
  components: ScoreComponents,
  weightedScore: z.number().min(0).max(100),
  riskPenalty: z.number().min(0),
  finalScore: z.number().min(0).max(100),
  verdict: ScoreVerdict,
  confidence: Confidence,
  /** Human-readable breakdown, generated by code, not by the model. */
  explanation: z.array(z.string()).default([]),
  computedAt: IsoDateTime,
});
export type ScoreSnapshot = z.infer<typeof ScoreSnapshot>;

export const Decision = z.object({
  id: DecisionId,
  procurementId: ProcurementId.optional(),
  taskId: TaskId.optional(),
  kind: HumanDecisionKind,
  madeBy: UserId,
  comment: z.string().optional(),
  /** Score the specialist saw when deciding. */
  scoreSnapshotId: ScoreSnapshotId.optional(),
  madeAt: IsoDateTime,
});
export type Decision = z.infer<typeof Decision>;
